[[redirects]]
  from = "https://www.kopi.dev/*"
  to = "https://kopi.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://kopidev.netlify.com/*"
  to = "https://kopi.dev/:splat"
  status = 301
  force = true

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=604800"